### PR TITLE
3d model loading

### PR DESCRIPTION
**Pull request by atar13**
This PR adds the `Model` class which can load a model from a file. These [formats](https://assimp-docs.readthedocs.io/en/latest/about/introduction.html) are supported.

Instructions for downloading models is on the README of this branch. 

Texture loading is not working yet and needs further debugging. 

The one blocker right now is making sure it compiles on Windows (lab and GitHub actions). I'm working on figuring this out but before then I'd like to get some thoughts on the code.

Originally I was going to write my own parser (take one from a tutorial or CSE167). However, it was getting a bit cumbersome and there were many model format variations that I had to handle. Instead, I opted to use the [Assimp library](https://assimp-docs.readthedocs.io/en/latest/about/introduction.html) to perform the model loading. It's been [recommended by previous 125 groups](https://cse125.ucsd.edu/tips/graphics.html) to reduce the complexity of loading models.

## 5/4 Update:
This PR grew out of just loading models and has turned into loading materials and textures. I think once we are able to load the player model it should be merged. 

- [x] loading models
- [x] moved models to assets folder
- [x] loading and rendering textures
- [x] loading and rendering model lighting materials
- [x] load Coco's player model
~~- [ ] initial light sources~~ (punting this to another PR)

### CODE REVIEW

**Comment by atar13** [comment]
Confirmed to work on lab machines

**Review by dmin12 — APPROVED** [review]
Everything works on my end (Apple silicon) and I see a very teal bearl. I'm glad you found a library for model loading, and from a brief look over the documentation it seems like it's going to save us a lot of time on all of the model and animation work.

**Review by Tyler-Lentz — APPROVED** [review]
Thanks for grinding this stuff out. Graphics programming gets me like :skull:

**Comment by atar13** [comment]
These commits got merged into #56

**Pull request closed without merging**
