### PR TITLE
sun god :fire:

### LINKED ISSUE #102: Make Sun God shoot fireballs
- [ ] load in sun god model w textures
- [ ] modify fireballs to come from sun god's beak

### PR DESCRIPTION
**Pull request by atar13**
closes #102 

NOTE: pull latest models/textures from drive

- sun god model
- sun god shoots fireballs
- fireballs only shoot in the direction sun god is facing
- fireball traps now have direction (see `gridcell.cpp`)
- fix windows gh action

### CODE REVIEW

**Review by Tyler-Lentz — CHANGES_REQUESTED** [review]
he forgor how to shoot fireball :(

**Comment by jhparkt** [comment]
> he forgor how to shoot fireball :(

model looks great tho!

**Comment by atar13** [comment]
> he forgor how to shoot fireball :(

For some reason having the Box collider enabled for the sun god doesn't allow fireballs to go through. I added the box collider in a last minute commit but never ran it again ... "Fixed" here by removing collider but idk if there's a way around it https://github.com/ucsd-cse125-sp24/group3/pull/139/commits/e2fe5924a9c062180f9e07ee1cb41bb6502ff258

**Review by Tyler-Lentz — CHANGES_REQUESTED** [review]
i hate to be this guy but i think one of the directions for the sun god might be messed up, see the following video


https://github.com/ucsd-cse125-sp24/group3/assets/22576354/7dfbe49c-046f-4cb3-b3d4-e29c5a18ce08



I tried looking through the code but it all passed my brain compiler... so I really don't know how this could even possibly be happening because it is very clearly facing the right direction in the world, and I saw it working correctly on your computer earlier today. I would need to look at this not at 1am :(

edit: ok so the gnome screen record is garbage on my laptop but you can see for like one frame how the sun god in front of me is shooting to the side (in the same direction as the one on the right)

**Review by Tyler-Lentz — APPROVED** [review]
i think you said you wanted to add a couple cleanups, but just preemptively approving so you can go right away once those are in and they work

**Pull request merged**
