### PR TITLE
doxygen with deployment via github actions

### PR DESCRIPTION
**Pull request by atar13**
## Local

Install [doxygen](https://www.doxygen.nl/download.html) locally and run `doxygen` in the root of the project. View the built `html` files in the `docs` directory. These generated docs are not tracked by Git.

## Remote

View docs [here](https://cse125.ucsd.edu/2024/cse125g3/site/docs/html/)

### CODE REVIEW

**Review by Tyler-Lentz — APPROVED** [review]
Thanks for setting this up, Anthony "DevOps" Tarbinian :+1:

**Comment by EddieJ03** [comment]
Is it supposed to say Asana? I clicked the remote link and it says Asana instead of Arcana.

**Comment by atar13** [comment]
> Is it supposed to say Asana? I clicked the remote link and it says Asana instead of Arcana.

lmao. i may have mistyped the game name

**Review by EddieJ03 — APPROVED** [review]
Lgtm

**Pull request merged**
