### PR TITLE
Wall Textures

### LINKED ISSUE #110: Texture Walls
Texture the walls using the texture that Coco made

### PR DESCRIPTION
**Pull request by atar13**
Closes #110 

NOTE: make sure to pull latest graphics assets from drive for testing

Load in wall + pillar textures into the maze. 

In map files all `#` characters are walls and `!` are pillars.

Screenshot from 2024-05-21 23-22-09
Screenshot from 2024-05-22 13-56-20
Screenshot from 2024-05-22 13-57-13

### CODE REVIEW

**Review by Tyler-Lentz — APPROVED** [review]
works on my machine and looks sweet!

**Comment by Tyler-Lentz** [comment]
tacked on an extra fix to the procedural generation to fix the 50% chance to not generate a maze

**Review by jhparkt — APPROVED** [review]
one of the biggest updates! works well on my end

**Review by EddieJ03 — APPROVED** [review]
goated change by a goated man

**Pull request merged**
