### PR TITLE
SFML Audio

### PR DESCRIPTION
**Pull request by EddieJ03**
We using SFML because it works (so far)

Pending Tasks
- [x] SFML On Windows
- [x]  SFML On Linux (ask Anthony if there are issues)
- [x] SDL On Mac
- [x] Actually try playing an audio file
- [x] Play music in background
- [x] Fix CI pipeline failing Linux

### CODE REVIEW

**Review by dmin12 — COMMENTED** [review]
Looks good overall, works on Apple silicon with a small workaround. I noticed that this has some of the changes that are in feat/creature-player-enemy-tree, do we need a pr for that branch too or is this one basically both?

**Review by jhparkt — APPROVED** [review]
Oh wow. Didn't expect the music to play. Good work. Works well both on my windows and mac (intel).

**Comment by gilkeidar** [comment]
Music plays for me as well! Works well on my Windows 11 desktop.

**Review by Tyler-Lentz — APPROVED** [review]
Piano :flushed:

**Comment by EddieJ03** [comment]
> Looks good overall, works on Apple silicon with a small workaround. I noticed that this has some of the changes that are in feat/creature-player-enemy-tree, do we need a pr for that branch too or is this one basically both?

Nah this branch was just meant for audio. I just made it up-to-date with what is in dev though (the camera PR), which I think already has the player-enemy-tree stuff.

**Comment by atar13** [comment]
Works on my end on Linux after adding a few packages to nix shell. Thanks for getting this all set up!

**Review by atar13 — APPROVED** [review]

**Pull request merged**
