### PR TITLE
Final Product

### PR DESCRIPTION
**Pull request by Tyler-Lentz**
We can merge this in before we build our program for the demo

### CODE REVIEW

**Comment by jerukan** [comment]
🔥🔥🔥🔥🔥 can't wait for the release 🔥🔥🔥🔥🔥🔥🔥

**Review by dmin12 — APPROVED** [review]
Great work gamers 🎉🎉🎉

**Review by atar13 — APPROVED** [review]
game is gaming

**Review by EddieJ03 — APPROVED** [review]
Looks great can’t wait for the demo!

**Review by jhparkt — APPROVED** [review]
⚡️⚡️ ⚡️⚡️ ⚡️⚡️ ⚡️⚡️

**Review by gilkeidar — APPROVED** [review]
Lgtm

**Pull request merged**
