### PR TITLE
set model dimensions

### PR DESCRIPTION
**Pull request by atar13**
This PR adds functionality to allow us to specify the exact dimensions that a model should be resized to with `Model::setDimensions`.

It also:
- Gets the model's initial bounding box by combining the bounding of each mesh
- Changed Renderable class to have absolute scaling methods
- Fixed an issue where the Warren bear wasn't textured (our lab testing seemed to bleed out into a commit on GitHub which is why the textures weren't rendering)
- Changed walls to be rendered from a cube OBJ file instead of the Cube class since it will be easier to add textures to
- Set some initial sizes for the bear and player models on the server side based on the dimensions that get printed out during model load time

### CODE REVIEW

**Review by Tyler-Lentz — CHANGES_REQUESTED** [review]
This change is really sweet, so thank you a lot. This should make managing the models very easy.

One thing though, can you repull the changes from dev? I think you are a little behind, like for example this branch still has a seg fault when you try and manually enter the IP address. Then we could use the "localhost" bug to get multiple models in the server and test whether or not the models line up with the ground / your eye level matches with other player's eye levels, and get that squared away

Also if #91 gets merged in first you might also have to pull those changes in

**Comment by atar13** [comment]
Merged in changes from dev and now drawing models with dimensions that are scalar multiples of their geometry's dimensions.

Two things to note:
1. Right now I'm making the player dimensions pretty small (1/4th of their model's dimensions) since
otherwise it collides with the maze passages and you
can't move around anywhere. we should eventually solve this
by tucking in the player's arms since right now they're
spread out in the model
2. I'm translating models using their corner instead of center position
since they were floating with the center position

**Review by Tyler-Lentz — APPROVED** [review]
thanks for getting this up to date,
one thing I noticed is that now that we're using the cube model everything is being rendered in the same red color. for testing purposes would it be possible to allow us to render cubes in different colors statically? it might be hard to test certain traps and stuff if everything is the same red color. (e.g. right now you can't really see the ceiling spike trap because it is blending in with the roof)

i dropped an approve so you can merge asap but hopefully we can make the tiny color change first?

**Comment by Tyler-Lentz** [comment]
or it doesnt have to be color but some method to be able to distinguish between different cubes until we have models and textures

**Comment by atar13** [comment]
The reason everything was showing up as red was that I accidentally was drawing the solidsurfaces with the same shader as the cube. I had changed the solidsurface to be a `Model` instead of `Cube` and `Model` interacts with the shader differently than `Cube` so it wasn't overwriting the color and the spike trap color just carried over. I probably shouldn't have messed with that in this PR, but I figured we were going to need to move over to use textures on the solidsurfaces.

If you want cubes to be different colors you can pass in  the color to the `Cube` constructor and make sure to use the `cube_shader` when calling `Cube::draw` since that will respect the color you set in the constructor.

Since solidsurfaces are now being rendered from a `Model` that loads an OBJ file, I added a corresponding material file on the drive. To get the updated model and material file, you'll need to download the updated `cube.obj` and `cube.mtl` from the drive.

**Comment by Tyler-Lentz** [comment]
Sweet, everything looks awesome with that update

**Comment by atar13** [comment]
Just added one small thing to draw bounding boxes around the player and bear. There shouldn't be any more features on this branch

**Comment by jerukan** [comment]
cool update

**Pull request merged**
